<?php
$urlPattern = $_SERVER['REQUEST_URI'];

$formatUrl = function($page) use ($urlPattern){
        if(!preg_match('/page/',$urlPattern))
                return $urlPattern . "/page/" . $page;
        else
                return preg_replace('/\d/', $page,$urlPattern);
    
    
};



?>

<?php if ($this->pageCount): ?>
<div class="paginationControl">
<?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>
de <?php echo $this->totalItemCount; ?> Páginas

<!-- First page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $formatUrl($this->first)?>">
    Primeira
  </a> |
<?php else: ?>
  <span class="disabled">Primeira</span> |
<?php endif; ?>

<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $formatUrl($this->previous) ?>">
    &lt; Anterior
  </a> |
<?php else: ?>
  <span class="disabled">&lt; Anterior</span> |
<?php endif; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $formatUrl($this->next) ?>">
    Próxima &gt;
  </a> |
<?php else: ?>
  <span class="disabled">Próxima &gt;</span> |
<?php endif; ?>

<!-- Last page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $formatUrl($this->last) ?>">
    Última
  </a>
<?php else: ?>
  <span class="disabled">Última</span>
<?php endif; ?>

</div>
<?php endif; ?>